-- EWAH Tech Platform — Completar catálogo de Países
-- Pega esto completo en Supabase → SQL Editor → New Query → Run
--
-- 0004_parametros.sql sembró solo 25 países (los más relevantes para
-- Latinoamérica) + "Otro". El usuario pidió la lista completa para que
-- Nacionalidad/País de residencia no obliguen a nadie a caer en "Otro".
-- Se insertan los que faltan (on conflict do nothing por si alguno ya
-- existe) y luego se recalcula el orden alfabético de TODA la tabla,
-- dejando "Otro" siempre al final — más práctico que mantener a mano el
-- número de orden de 190+ filas insertadas en bloque.

insert into paises (codigo, nombre) values
  -- Europa
  ('GB', 'Reino Unido'),
  ('PT', 'Portugal'),
  ('NL', 'Países Bajos'),
  ('BE', 'Bélgica'),
  ('CH', 'Suiza'),
  ('AT', 'Austria'),
  ('SE', 'Suecia'),
  ('NO', 'Noruega'),
  ('DK', 'Dinamarca'),
  ('FI', 'Finlandia'),
  ('IS', 'Islandia'),
  ('IE', 'Irlanda'),
  ('PL', 'Polonia'),
  ('CZ', 'República Checa'),
  ('SK', 'Eslovaquia'),
  ('HU', 'Hungría'),
  ('RO', 'Rumania'),
  ('BG', 'Bulgaria'),
  ('GR', 'Grecia'),
  ('HR', 'Croacia'),
  ('SI', 'Eslovenia'),
  ('RS', 'Serbia'),
  ('BA', 'Bosnia y Herzegovina'),
  ('ME', 'Montenegro'),
  ('MK', 'Macedonia del Norte'),
  ('AL', 'Albania'),
  ('XK', 'Kosovo'),
  ('UA', 'Ucrania'),
  ('BY', 'Bielorrusia'),
  ('RU', 'Rusia'),
  ('MD', 'Moldavia'),
  ('LT', 'Lituania'),
  ('LV', 'Letonia'),
  ('EE', 'Estonia'),
  ('LU', 'Luxemburgo'),
  ('MT', 'Malta'),
  ('CY', 'Chipre'),
  ('MC', 'Mónaco'),
  ('AD', 'Andorra'),
  ('SM', 'San Marino'),
  ('LI', 'Liechtenstein'),
  ('VA', 'Ciudad del Vaticano'),
  -- América
  ('BZ', 'Belice'),
  ('JM', 'Jamaica'),
  ('HT', 'Haití'),
  ('BS', 'Bahamas'),
  ('TT', 'Trinidad y Tobago'),
  ('BB', 'Barbados'),
  ('GY', 'Guyana'),
  ('SR', 'Surinam'),
  ('AG', 'Antigua y Barbuda'),
  ('DM', 'Dominica'),
  ('GD', 'Granada'),
  ('KN', 'San Cristóbal y Nieves'),
  ('VC', 'San Vicente y las Granadinas'),
  ('LC', 'Santa Lucía'),
  -- Asia
  ('CN', 'China'),
  ('JP', 'Japón'),
  ('KR', 'Corea del Sur'),
  ('KP', 'Corea del Norte'),
  ('IN', 'India'),
  ('PK', 'Pakistán'),
  ('BD', 'Bangladés'),
  ('LK', 'Sri Lanka'),
  ('NP', 'Nepal'),
  ('BT', 'Bután'),
  ('MV', 'Maldivas'),
  ('AF', 'Afganistán'),
  ('IR', 'Irán'),
  ('IQ', 'Irak'),
  ('SA', 'Arabia Saudita'),
  ('AE', 'Emiratos Árabes Unidos'),
  ('QA', 'Catar'),
  ('KW', 'Kuwait'),
  ('BH', 'Baréin'),
  ('OM', 'Omán'),
  ('YE', 'Yemen'),
  ('JO', 'Jordania'),
  ('LB', 'Líbano'),
  ('SY', 'Siria'),
  ('IL', 'Israel'),
  ('PS', 'Palestina'),
  ('TR', 'Turquía'),
  ('GE', 'Georgia'),
  ('AM', 'Armenia'),
  ('AZ', 'Azerbaiyán'),
  ('KZ', 'Kazajistán'),
  ('UZ', 'Uzbekistán'),
  ('TM', 'Turkmenistán'),
  ('TJ', 'Tayikistán'),
  ('KG', 'Kirguistán'),
  ('MN', 'Mongolia'),
  ('VN', 'Vietnam'),
  ('TH', 'Tailandia'),
  ('MM', 'Myanmar'),
  ('LA', 'Laos'),
  ('KH', 'Camboya'),
  ('MY', 'Malasia'),
  ('SG', 'Singapur'),
  ('ID', 'Indonesia'),
  ('PH', 'Filipinas'),
  ('BN', 'Brunéi'),
  ('TL', 'Timor Oriental'),
  ('TW', 'Taiwán'),
  -- Oceanía
  ('AU', 'Australia'),
  ('NZ', 'Nueva Zelanda'),
  ('PG', 'Papúa Nueva Guinea'),
  ('FJ', 'Fiyi'),
  ('SB', 'Islas Salomón'),
  ('VU', 'Vanuatu'),
  ('WS', 'Samoa'),
  ('TO', 'Tonga'),
  ('KI', 'Kiribati'),
  ('FM', 'Micronesia'),
  ('PW', 'Palaos'),
  ('MH', 'Islas Marshall'),
  ('NR', 'Nauru'),
  ('TV', 'Tuvalu'),
  -- África
  ('ZA', 'Sudáfrica'),
  ('NG', 'Nigeria'),
  ('EG', 'Egipto'),
  ('MA', 'Marruecos'),
  ('DZ', 'Argelia'),
  ('TN', 'Túnez'),
  ('LY', 'Libia'),
  ('SD', 'Sudán'),
  ('SS', 'Sudán del Sur'),
  ('ET', 'Etiopía'),
  ('KE', 'Kenia'),
  ('TZ', 'Tanzania'),
  ('UG', 'Uganda'),
  ('RW', 'Ruanda'),
  ('BI', 'Burundi'),
  ('SO', 'Somalia'),
  ('DJ', 'Yibuti'),
  ('ER', 'Eritrea'),
  ('GH', 'Ghana'),
  ('CI', 'Costa de Marfil'),
  ('SN', 'Senegal'),
  ('ML', 'Malí'),
  ('BF', 'Burkina Faso'),
  ('NE', 'Níger'),
  ('TD', 'Chad'),
  ('CM', 'Camerún'),
  ('CF', 'República Centroafricana'),
  ('GA', 'Gabón'),
  ('CG', 'República del Congo'),
  ('CD', 'República Democrática del Congo'),
  ('AO', 'Angola'),
  ('ZM', 'Zambia'),
  ('ZW', 'Zimbabue'),
  ('MZ', 'Mozambique'),
  ('NA', 'Namibia'),
  ('BW', 'Botsuana'),
  ('LS', 'Lesoto'),
  ('SZ', 'Esuatini'),
  ('MG', 'Madagascar'),
  ('MU', 'Mauricio'),
  ('SC', 'Seychelles'),
  ('KM', 'Comoras'),
  ('CV', 'Cabo Verde'),
  ('GW', 'Guinea-Bisáu'),
  ('GN', 'Guinea'),
  ('GQ', 'Guinea Ecuatorial'),
  ('SL', 'Sierra Leona'),
  ('LR', 'Liberia'),
  ('TG', 'Togo'),
  ('BJ', 'Benín'),
  ('GM', 'Gambia'),
  ('MR', 'Mauritania'),
  ('ST', 'Santo Tomé y Príncipe')
on conflict (codigo) do nothing;

-- Reordena alfabéticamente toda la tabla (menos "Otro", que se queda al final).
update paises set orden = sub.rn
from (
  select id, row_number() over (order by nombre) as rn
  from paises
  where codigo is distinct from 'OTRO'
) sub
where paises.id = sub.id;

update paises set orden = 999 where codigo = 'OTRO';
